name: 'SecurityCodeScan'
description: 'Security Code Scan action to add NuGet packages and set up projects'
branding:
  icon: 'check-circle'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - name: Set up Security-Code-Scan
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop";

        foreach($project in Get-ChildItem -Path . -Filter *.csproj -Recurse -Force) {
          dotnet add $project package SecurityCodeScan.VS2019
          
          $xml = [xml](Get-Content -Path $project)

          $errorLog = $xml.CreateElement("ErrorLog")
          $errorLog.set_InnerText("analysis.sarif")
          $propertyGroups = $xml.SelectNodes("//Project/PropertyGroup")
          $propertyGroups[0].AppendChild($errorLog)

          $xml.Save($project)
        }

        foreach($project in Get-ChildItem -Path . -Filter *.vbproj -Recurse -Force) {
          dotnet add $project package SecurityCodeScan.VS2019
          
          $xml = [xml](Get-Content -Path $project)

          $errorLog = $xml.CreateElement("ErrorLog")
          $errorLog.set_InnerText("analysis.sarif")
          $propertyGroups = $xml.SelectNodes("//Project/PropertyGroup")
          $propertyGroups[0].AppendChild($errorLog)

          $xml.Save($project)
        }
